---
apiVersion: v1
kind: Service
metadata:
  name: eschool-frontend-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  frontend_mapping
      prefix: /
      host: eschool2.chaincorp.info
      service: eschool-frontend-service
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  backend_redirect_mapping
      prefix: /api/
      service: api2.eschool.chaincorp.info
      host_redirect: true
spec:
  selector:
    app: eschool-frontend
  ports:
  - port: 80
    targetPort: 80
    name: port-frontend