apiVersion: v1
kind: Service
metadata: 
  name: eschool-backend-service
spec: 
  ports: 
     -  port: 8080
        protocol: TCP
        targetPort: 8080
        name: port-backend
  selector: 
    app: eschool-backend
  type: NodePort