apiVersion: v1
kind: Service
metadata: 
  name: eschool-frontend-service
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 80
        name: port-frontend
  selector: 
    app: eschool-frontend
  type: NodePort